language: php

cache:
  directories:
    - $HOME/.composer/cache/files

# https://docs.travis-ci.com/user/build-stages

jobs:

  include:

    - stage: test

      php: 7.3

      before_script:
        - travis_retry composer self-update
        - travis_retry composer update --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts

      script:
        - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

    - stage: deploy

      name: "Documentation"

      php: 7.3

      before_script:
        - git clone https://github.com/mtvbrianking/laravel-mtn-momo.git

      script:
       - vendor/bin/doctum.php update doctum.php

      # https://docs.travis-ci.com/user/deployment/pages/
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        local_dir: docs
        on:
          branch: master

# https://docs.travis-ci.com/user/notifications
notifications:
  email:
    on_success: never
    on_failure: always
