# https://docs.travis-ci.com/user/build-stages

language: php

php:
  - 7.2

# Default stage = test,
# Runs for both default php versions - above.

before_script:
  - travis_retry composer self-update
  - travis_retry composer update --prefer-lowest --no-ansi --no-interaction --no-progress --no-scripts

script:
 - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

# jobs:

#   include:

#     - stage: deploy

#       name: Documentation

#       php: 7.2

#       install:
#         - curl -O http://get.sensiolabs.org/sami.phar

#       script:
#        - php sami.phar update .sami

#       # https://docs.travis-ci.com/user/deployment/pages/
#       deploy:
#         provider: pages
#         skip-cleanup: true
#         github-token: $GITHUB_TOKEN
#         local_dir: docs
#         on:
#           branch: master

